# Form implementation generated from reading ui file 'src/screen_ui/start_screen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 218)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 10, 231, 101))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(10, 180, 113, 32))
        self.exit_button.setObjectName("exit_button")
        self.setting_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.setting_button.setGeometry(QtCore.QRect(140, 140, 151, 32))
        self.setting_button.setObjectName("setting_button")
        self.rules_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rules_button.setGeometry(QtCore.QRect(310, 180, 113, 32))
        self.rules_button.setObjectName("rules_button")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(160, 180, 113, 32))
        self.start_button.setObjectName("start_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Начало игры"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Marker Felt\'; font-size:36pt; font-weight:600;\">Нет уж,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Marker Felt\'; font-size:36pt; font-weight:600; color:#fc0107;\">Спасибо!</span></p></body></html>"))
        self.exit_button.setText(_translate("MainWindow", "Выход"))
        self.setting_button.setText(_translate("MainWindow", "Начать настройку"))
        self.rules_button.setText(_translate("MainWindow", "Правила"))
        self.start_button.setText(_translate("MainWindow", "Начать"))
